openapi: "3.0.0"

info:
  title: "Bayesian network of B.pertussis isolated strains."
  description: "API that accepts a list [Period, Clade, ptxP, prn, fim3] and calculated the conditional probabilites of the missing values."
  version: "1.0"

paths:
  /bayesian:
    post:
      description: "Known B.pertussis isolated strain variables."

      requestBody:
        description: "list [Period, Clade, ptxP, prn, fim3]"
        required: true
        content:
          application/json: {}

      responses:
        '200':
          description: "Returns conditional probabilities of the missing values in html table format."
          content: 
           text/html:
              schema:
                type: string
           
    get:
      responses:
        '200':
          description: "Returns the html page to make submits."
          content:
            text/html:
              schema:
                type: string